<?php

namespace AppBundle\Repository\Article;

/**
 * ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListRepository extends \Doctrine\ORM\EntityRepository
{
}
